config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :home

  get "tasks/new", to: "tasks#new", as: :new

  post "tasks", to: "tasks#create"

  get "tasks/:id", to: "tasks#show", as: :task

  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  delete 'tasks/:id', to: 'tasks#delete', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :find_task, only: [:show, :edit, :update, :destroy]
    
  def index
    @tasks = Task.all
  end

  def show
    #@task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    #@task = Task.find(params[:id])
  end

  def update
    #@task = Task.find(params[:id])
    @task.update(tasks_params)

    redirect_to task_path(@task)
  end

  def delete
    #@task = Task.find(params[:id])
    @task.destroy

    redirect_to home_path
  end


  private

  def find_task
    @task = Task.find(params[:id])
  end

  def tasks_params
    params.require(:task).permit(:name, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="form-group">
<%= simple_form_for(@task) do |f| %>
<%= f.input :name %>
<%= f.input :details %>
<%= f.input :completed, collection: [true, false] %>
<%= f.submit class: "btn btn-info" %>

<% end %>
</div>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.name %></h1>

<%= render 'form' %>

<h3><%= link_to 'Please take me back', home_path %></h3>

app/views/tasks/index.html.erb
<h1>Roao's first view 🚀</h1>

<% @tasks.each do |task| %>
  <li>
    <%= link_to task.name, task_path(task) %> <%= task.completed ? '☑️' : '☐' %>
  </li>
<% end %>

<h3><%= link_to 'Add a new task', new_path %></h3>

app/views/tasks/new.html.erb
<h1>Edit <%= @task.name %></h1>

<%= render 'form' %>

<h3><%= link_to 'Please take me back', home_path %></h3>

app/views/tasks/show.html.erb
<h1>Show Task Page</h1>

<p><%= @task.details %></p>

<h3><%= link_to 'Edit task', edit_task_path(@task) %></h3>

<h3><%= link_to 'Please take me back', home_path %></h3>

<%= link_to "Delete", delete_task_path(@task), method: :delete , data: { confirm: "are you sure?"} %>